### ISSUE TITLE
question about programming of the MCU

### ISSUE THREAD

**Issue by jerabaul29** [eivholt/snowmonitor#1]
Many thanks for making this exciting project open :) .

A small question: if I understand well you used a Wio-E5 mini (STM32WLE5JC) Dev Board as the heart of the project, right ( https://www.seeedstudio.com/LoRa-E5-mini-STM32WLE5JC-p-4869.html ) ?

I am a n00b working with these STM32 MCUs, and I try to get started using it, can you confirm that the process was to:

- use CubeIDE + a ST-Link programmer to remove the RDP protection; do you know if there is a detailed tutorial "for n00bs" about how to do this (including wiring and steps description? I would like to avoid damaging my board :) )?
- from there, can you confirm that the bootloader allows directly uploading code on the board through the USB port? Or did you continue using the ST-Link to upload code?

**Comment by jerabaul29** [comment]
Ok, found the details in the hackster article https://www.hackster.io/eivholt/low-power-snow-depth-sensor-using-lora-e5-b8e7b8 :) . Putting it here for self contained documentation on GH :) .

![Screenshot from 2022-08-16 21-18-14](https://user-images.githubusercontent.com/8382834/184966228-eeb1f813-2377-400e-9b07-57d7085a1009.png)

**Comment by eivholt** [comment]
Hi, thanks for the question - and the answer. I couldn't remember how I did the connection, thankfully I had documented it in the article. I hope seeed will clarify this in their wiki. Good luck on your projects!
